# Generated by Django 4.2.6 on 2023-10-31 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contract_id_equipment_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loan'),
        ),
    ]
