# Generated by Django 4.2.6 on 2023-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_equipment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ownership',
            field=models.CharField(choices=[('Financed', 'Financed'), ('Rental', 'Rental'), ('InterCo', 'Inter Company Rental'), ('Leased', 'Leased'), ('Owned', 'Owned w/ Title'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(choices=[('Financed', 'Financed'), ('Rental', 'Rental'), ('InterCo', 'Inter Company Rental'), ('Leased', 'Leased'), ('Owned', 'Owned w/ Title'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
