# Generated by Django 4.2.6 on 2023-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_equipment_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='down_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='financed_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_term',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_payments',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
