# Generated by Django 4.2.6 on 2023-10-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_loan_down_payment_loan_financed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='financed_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
