# Generated by Django 4.2.6 on 2023-11-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_loan_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_satisfied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ownership',
            field=models.CharField(choices=[('Financed', 'Financed'), ('Rental', 'Rental'), ('InterCo', 'Inter Company Rental'), ('Leased', 'Leased'), ('Owned', 'Owned w/ Title'), ('Sold', 'Sold'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
