# Generated by Django 4.2.6 on 2023-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_loan_loan_satisfied_date_loan_loan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ownership',
            field=models.CharField(choices=[('Financed', 'Financed'), ('Rental', 'Rental'), ('InterCo', 'Inter Company Rental'), ('Leased', 'Leased'), ('Owned', 'Owned'), ('Sold', 'Sold'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Satisfied', 'Satisfied')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(choices=[('Financed', 'Financed'), ('Rental', 'Rental'), ('InterCo', 'Inter Company Rental'), ('Leased', 'Leased'), ('Owned', 'Owned w/ Title'), ('Newly Owned', 'Owned w/o Title'), ('Sold', 'Sold'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
