# Generated by Django 4.2.6 on 2023-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_equipment_status_vehicle_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='link_to_contract',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
