# Generated by Django 4.2.6 on 2023-11-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_equipment_options_alter_loan_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
