# Generated by Django 4.2.6 on 2023-11-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_location_active_jobsite'),
        ('api', '0014_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.location'),
        ),
    ]
