# Generated by Django 4.2.6 on 2023-11-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_remove_profile_vehicle'),
        ('api', '0015_equipment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.profile'),
        ),
    ]
