# Generated by Django 4.2.6 on 2023-11-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_vehicle_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
    ]
