# Generated by Django 4.2.6 on 2023-11-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_equipment_contract_remove_equipment_location_and_more'),
        ('finance', '0008_alter_equippayoff_equipment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
