# Generated by Django 4.2.6 on 2023-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
