# Generated by Django 4.2.6 on 2023-11-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active_jobsite',
            field=models.BooleanField(default=False),
        ),
    ]
