# Generated by Django 4.2.6 on 2023-11-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_location_active_jobsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
    ]
