# Generated by Django 4.2.6 on 2023-11-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_equipment_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.location'),
        ),
    ]
