# Generated by Django 4.2.6 on 2023-11-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_equippayoff_options_and_more'),
        ('asset', '0005_equipment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.loan'),
        ),
    ]
