# Generated by Django 4.2.6 on 2023-11-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payoff',
            old_name='dvalid_thru',
            new_name='valid_thru',
        ),
    ]
