# Generated by Django 4.2.6 on 2023-11-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_dvalid_thru_payoff_valid_thru'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payoff',
        ),
    ]
