# Generated by Django 4.2.6 on 2023-11-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_vehicle_vin'),
        ('finance', '0002_remove_equippayoff_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equippayoff',
            options={'ordering': ['equipment']},
        ),
        migrations.AlterModelOptions(
            name='vehiclepayoff',
            options={'ordering': ['vehicle']},
        ),
        migrations.CreateModel(
            name='LenderLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('customer_serv_num', models.CharField(max_length=10)),
                ('mfa_num', models.CharField(max_length=10)),
                ('security_one', models.CharField()),
                ('answer_one', models.CharField()),
                ('security_two', models.CharField()),
                ('answer_two', models.CharField()),
                ('security_three', models.CharField()),
                ('answer_three', models.CharField()),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.loan')),
            ],
        ),
    ]
