# Generated by Django 4.2.6 on 2023-11-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0013_alter_equipment_options_alter_loan_options_and_more'),
        ('finance', '0003_delete_payoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payoff', models.FloatField(blank=True, null=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('valid_thru', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.loan')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
