# Generated by Django 4.2.6 on 2023-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_lenderlogin_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderlogin',
            name='answer_one',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='answer_three',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='answer_two',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='customer_serv_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='mfa_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='security_one',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='security_three',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='security_two',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lenderlogin',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
