# Generated by Django 4.2.6 on 2023-11-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoff',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='payoff',
            name='vehicle',
        ),
    ]
