# Generated by Django 4.2.6 on 2023-11-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_lenderlogin_answer_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lenderlogin',
            options={'ordering': ['lender']},
        ),
    ]
