# Generated by Django 4.2.6 on 2023-11-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_lenderlogin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_to_contract', models.URLField(blank=True, max_length=300, null=True)),
                ('lender', models.CharField(max_length=40)),
                ('owned_company', models.CharField(max_length=25)),
                ('contract_number', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('loan_term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('down_payment', models.IntegerField(blank=True, null=True)),
                ('financed_amount', models.FloatField(blank=True, null=True)),
                ('monthly_payment', models.FloatField(blank=True, null=True)),
                ('remaining_payments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('loan_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Satisfied', 'Satisfied')], default='Active', max_length=20, null=True)),
                ('loan_satisfied_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['lender', 'contract_number'],
            },
        ),
    ]
