# Generated by Django 4.2.6 on 2023-11-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_equipment_vehicle'),
        ('finance', '0007_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equippayoff',
            name='equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.equipment'),
        ),
        migrations.AlterField(
            model_name='vehiclepayoff',
            name='vehicle',
            field=models.OneToOneField(db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.vehicle'),
        ),
    ]
