# Generated by Django 4.2.6 on 2023-11-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_equippayoff_equipment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equippayoff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehiclepayoff',
            options={},
        ),
        migrations.RemoveField(
            model_name='equippayoff',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='vehiclepayoff',
            name='vehicle',
        ),
    ]
